# backend_rpc_server_core.py
# This file defines the core Python backend server as an OOP class.
# It orchestrates the voice control pipeline, handles RPC communication,
# and serves as the main entry point for the backend.

import importlib
import json
import sys
import textwrap
from typing import Any

from ..common.utils import map_json_type_to_python


class ToolCaller:
    def __init__(self, tool_client: Any):
        self.tool_client = tool_client

    def __call__(self, response: str, tool_calls: list[dict]):
        tts_response = ""

        for tool_call in tool_calls:
            tool_name = tool_call.get("name")
            tool_args = tool_call.get("args", {})

            rpc_method = getattr(self.toos_api, tool_name)
            res, err = rpc_method(**tool_args)
            if err:
                raise Exception(f"Error occurred with {tool_name}: {err}.")

            tts_response += res.strip() + "\n"

        return tts_response


def parse_api_spec(filepath: str) -> list[dict[str, Any]]:
    """
    Parses an RPC API specification from a JSON file.

    Args:
        filepath: The path to the JSON specification file.

    Returns:
        A list of method dictionaries defined in the spec.
    """
    with open(filepath, "r", encoding="utf-8") as f:
        spec = json.load(f)
    methods = spec.get("methods", [])
    return methods


def get_client_class(self, tools_spec: list[dict[str, Any]]):
    """
    Dynamically generates the tool call stub code and loads it into memory.
    """
    stub_code = _generate_stub_code(tools_spec)

    module_name = "tools_stub_" + str(id(self))
    spec = importlib.util.spec_from_loader(module_name, loader=None)
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    exec(stub_code, module.__dict__)

    ToolClient = getattr(module, "ToolClient")

    return ToolClient


def _generate_stub_code(tools_spec: list[dict[str, Any]]):
    """
    Generates the Python client stub for tool calls through ZeroMQ RPC.

    Args:
        tools_spec: A list of dictionaries, where each dictionary defines an RPC method.
                    Expected format for each method:
                    {
                        "name": "method_name",
                        "description": "Description of the method.",
                        "params": [
                            {"name": "param1", "type": "string", "description": "Desc of param1"},
                            {"name": "param2", "type": "integer", "description": "Desc of param2"}
                        ]
                    }
    """
    template = textwrap.dedent(
        """
    # THIS FILE IS AUTO-GENERATED BY your_tool_generator_script.py. DO NOT EDIT MANUALLY.
    # Generated Python Client Stub for Lua Game Server API via ZeroMQ.

    import zmq
    import json
    import os
    import sys
    from typing import Any, Dict, List, Optional, Union

    class ToolClient:
        def __init__(self, endpoint: str, protocol: str = "tcp"):
            self.protocol = protocol
            self.endpoint = endpoint

            if self.protocol == "tcp":
                assert self.endpoint.startswith("tcp://")
            elif self.protocol == "ipc":
                assert self.endpoint.startswith("ipc://")
            else:
                raise ValueError(f"Unsupported protocol: {{self.protocol}}")

            self.context = zmq.Context()
            self.socket = self.context.socket(zmq.REQ)
            self.socket.set_string_option(zmq.RCVTIMEO, 5000) # 5 seconds receive timeout
            self.socket.set_string_option(zmq.SNDTIMEO, 5000) # 5 seconds send timeout
            
            try:
                self.socket.connect(self.endpoint)
                print(f"[ToolClient] Connected to {{self.endpoint}}")
            except zmq.ZMQError as e:
                print(f"[ToolClient] Failed to connect: {{e}}", file=sys.stderr)
                raise

            self.id_counter = 0

        def _send_rpc_request(self, method_name: str, *args):
            self.id_counter += 1
            request_body = {
                "jsonrpc": "2.0",
                "method": method_name,
                "params": list(args), # JSON-RPC params can be an array/list
                "id": self.id_counter
            }
            encoded_request = json.dumps(request_body)

            try:
                self.socket.send_string(encoded_request)
                response_str = self.socket.recv_string()
            except zmq.Again as e: # Timeout occurred
                print(f"[ToolClient] ZeroMQ timeout during request: {{e}}. Reconnecting socket...", file=sys.stderr)
                self.socket.close()
                self.socket = self.context.socket(zmq.REQ)
                self.socket.set_string_option(zmq.RCVTIMEO, 5000)
                self.socket.set_string_option(zmq.SNDTIMEO, 5000)
                self.socket.connect(self.endpoint)
                raise RuntimeError(f"ZeroMQ timeout. Socket reconnected, please retry.") from e
            except zmq.ZMQError as e:
                print(f"[ToolClient] ZeroMQ error during request: {{e}}. Reconnecting socket...", file=sys.stderr)
                self.socket.close()
                self.socket = self.context.socket(zmq.REQ)
                self.socket.set_string_option(zmq.RCVTIMEO, 5000)
                self.socket.set_string_option(zmq.SNDTIMEO, 5000)
                self.socket.connect(self.endpoint)
                raise RuntimeError(f"ZeroMQ error. Socket reconnected, please retry.") from e

            if not response_str:
                raise RuntimeError("Empty response from server.")

            decoded_response = json.loads(response_str)

            if decoded_response.get("jsonrpc") != "2.0":
                raise ValueError("Invalid JSON-RPC version in response.")
            
            if decoded_response.get("error"):
                err_obj = decoded_response["error"]
                raise RuntimeError(f"RPC Error (Code {{err_obj.get('code', -1)}}): {{err_obj.get('message', 'Unknown error')}}")

            if decoded_response.get("id") != request_body["id"]:
                raise ValueError(f"Mismatched RPC response ID. Expected {{request_body['id']}}, got {{decoded_response.get('id')}}")

            if "result" in decoded_response:
                return decoded_response["result"]
            else:
                raise ValueError("Missing 'result' field in successful JSON-RPC response.")

        def close(self):
            if self.socket:
                self.socket.close()
            if self.context:
                self.context.term()
            print("[ToolClient] ZeroMQ client closed.")

    {method_defs}

    """
    )

    method_template = textwrap.dedent(
        """
        def {name}(self{params_with_types}):
            \"\"\"
            {description}
            \"\"\"
            return self._send_rpc_request("{name}"{param_args})
    """
    )
    method_defs = []
    for method in tools_spec:
        params_with_types = ""
        param_args = ""
        if method.get("params"):  # Use .get() for robustness
            params_with_types = ", " + ", ".join(
                [
                    f"{p['name']}: {map_json_type_to_python(p['type'])}"
                    for p in method["params"]
                ]
            )
            param_args = ", " + ", ".join([p["name"] for p in method["params"]])

        method_defs.append(
            method_template.format(
                name=method["name"],
                description=method.get(
                    "description", "No description provided."
                ),  # Use .get()
                params_with_types=params_with_types,
                param_args=param_args,
            )
        )

    code = template.format(method_defs="\n".join(method_defs).strip())

    return code
